name: MCDataLink
version: '${project.version}'
main: org.tobias.mcdatalink.MCDataLink
api-version: '1.17'
authors: [Tobias Auer]
description: Connects to the server to provide the in-game stats
website: www.t-auer.com
